ALTER TABLE deals
    ADD COLUMN IF NOT EXISTS dispute_reason TEXT,
    ADD COLUMN IF NOT EXISTS dispute_opened_by INTEGER REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS dispute_opened_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS buyer_rating INTEGER,
    ADD COLUMN IF NOT EXISTS seller_rating INTEGER;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS completed_deals INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rating_total INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rating_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS deal_feedback (
    id SERIAL PRIMARY KEY,
    deal_id INTEGER NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
    reviewer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewee_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (deal_id, reviewer_user_id)
);
